# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ocr2txt.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rocr2txt.proto\"D\n\x0bpredict_req\x12\x0e\n\x06input1\x18\x01 \x01(\t\x12\x11\n\tfileName2\x18\x02 \x01(\t\x12\x12\n\nfileBytes2\x18\x03 \x01(\x0c\"\x1f\n\x0cpredict_resp\x12\x0f\n\x07output1\x18\x01 \x01(\t23\n\x07ocr2txt\x12(\n\x07predict\x12\x0c.predict_req\x1a\r.predict_resp\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ocr2txt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICT_REQ']._serialized_start=17
  _globals['_PREDICT_REQ']._serialized_end=85
  _globals['_PREDICT_RESP']._serialized_start=87
  _globals['_PREDICT_RESP']._serialized_end=118
  _globals['_OCR2TXT']._serialized_start=120
  _globals['_OCR2TXT']._serialized_end=171
# @@protoc_insertion_point(module_scope)
